CREATE TABLE PERSON(
 id BIGINT NOT NULL PRIMARY KEY,
 name VARCHAR(100)
);

CREATE TABLE LOCATION(
 reference_id BIGINT NOT NULL,
 latitude DOUBLE NOT NULL,
 longitude DOUBLE NOT NULL,
  FOREIGN KEY (reference_id) REFERENCES Person(id)
);

INSERT INTO PERSON VALUES (1, 'a');
INSERT INTO PERSON VALUES (2, 'b');
INSERT INTO PERSON VALUES (3, 'c');
INSERT INTO PERSON VALUES (4, 'd');
INSERT INTO PERSON VALUES (5, 'e');

INSERT INTO LOCATION VALUES (1,0.5,1.0);
INSERT INTO LOCATION VALUES (2,0.5,1.0);
INSERT INTO LOCATION VALUES (3,1.5,1.0);
INSERT INTO LOCATION VALUES (4,1.5,1.0);
INSERT INTO LOCATION VALUES (5,0.5,1.0);

